/*
 * JAboutDialog.java
 *
 */

package chat;


import javax.swing.*;

/**
 * the standard JChat About Box
 * @author  Herval
 * @version 0.5b
 * Created on: 22/03/2001
 * Last review: 25/03/2001
 */
public class JAboutDialog extends JDialog {

    /** Creates new form JAboutDialog */
    public JAboutDialog(java.awt.Frame parent,boolean modal) {
        super (parent, modal);
        initComponents ();
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents () {//GEN-BEGIN:initComponents
        jTextArea1 = new javax.swing.JTextArea ();
        jButton1 = new javax.swing.JButton ();
        getContentPane ().setLayout (new java.awt.FlowLayout ());
        setName ("About");
        setTitle ("Sobre este projeto");
        setResizable (false);
        setDefaultCloseOperation (javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener (new java.awt.event.WindowAdapter () {
            public void windowClosing (java.awt.event.WindowEvent evt) {
                closeDialog (evt);
            }
        }
        );

        jTextArea1.setEditable (false);
        jTextArea1.setText ("JChat versao 0.5 beta\nSistema de chat cliente servidor simples\n\nDesenvolvimento:\n\tHerval Freire de A. J\u00fanior\n\tLuciana Leal\n\tSabrina Fabel");


        getContentPane ().add (jTextArea1);

        jButton1.setText ("OK!");
        jButton1.addActionListener (new java.awt.event.ActionListener () {
            public void actionPerformed (java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed (evt);
            }
        }
        );


        getContentPane ().add (jButton1);

    }//GEN-END:initComponents

  private void jButton1ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
	JAboutDialog.this.dispose();
    
  }//GEN-LAST:event_jButton1ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new JAboutDialog (new javax.swing.JFrame (), true).show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}